package ar.edu.ubp.das.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-11-08T14:02:34.971-03:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://ws.das.ubp.edu.ar/", name = "LoginWS")
@XmlSeeAlso({ObjectFactory.class})
public interface LoginWS {

    @WebMethod(action = "urn:GetUsuario")
    @RequestWrapper(localName = "getUsuario", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.GetUsuario")
    @ResponseWrapper(localName = "getUsuarioResponse", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.GetUsuarioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ar.edu.ubp.das.ws.UsuarioBean getUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
