
package ar.edu.ubp.das.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-11-08T14:02:34.861-03:00
 * Generated source version: 3.2.6
 *
 */
public final class LoginWS_LoginWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.das.ubp.edu.ar/", "LoginWSService");

    private LoginWS_LoginWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LoginWSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        LoginWSService ss = new LoginWSService(wsdlURL, SERVICE_NAME);
        LoginWS port = ss.getLoginWSPort();

        {
        System.out.println("Invoking getUsuario...");
        java.lang.String _getUsuario_arg0 = "_getUsuario_arg0876046684";
        java.lang.String _getUsuario_arg1 = "_getUsuario_arg1-1832132984";
        ar.edu.ubp.das.ws.UsuarioBean _getUsuario__return = port.getUsuario(_getUsuario_arg0, _getUsuario_arg1);
        System.out.println("getUsuario.result=" + _getUsuario__return);


        }

        System.exit(0);
    }

}
