
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ar.edu.ubp.das.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-11-08T14:02:34.956-03:00
 * Generated source version: 3.2.6
 *
 */

@javax.jws.WebService(
                      serviceName = "LoginWSService",
                      portName = "LoginWSPort",
                      targetNamespace = "http://ws.das.ubp.edu.ar/",
                      wsdlLocation = "http://localhost:9090/LoginWSPort?wsdl",
                      endpointInterface = "ar.edu.ubp.das.ws.LoginWS")

public class LoginWSPortImpl implements LoginWS {

    private static final Logger LOG = Logger.getLogger(LoginWSPortImpl.class.getName());

    /* (non-Javadoc)
     * @see ar.edu.ubp.das.ws.LoginWS#getUsuario(java.lang.String arg0, java.lang.String arg1)*
     */
    public ar.edu.ubp.das.ws.UsuarioBean getUsuario(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation getUsuario");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            ar.edu.ubp.das.ws.UsuarioBean _return = new ar.edu.ubp.das.ws.UsuarioBean();
            _return.setApellido("Apellido-1472080441");
            _return.setNombre("Nombre-1595534441");
            _return.setNroDocumento("NroDocumento410212310");
            _return.setNroPersona(-229784011);
            _return.setTipoDocumento("TipoDocumento927145851");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
