package ar.edu.ubp.das.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-11-08T14:02:34.979-03:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "LoginWSService",
                  wsdlLocation = "http://localhost:9090/LoginWSPort?wsdl",
                  targetNamespace = "http://ws.das.ubp.edu.ar/")
public class LoginWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.das.ubp.edu.ar/", "LoginWSService");
    public final static QName LoginWSPort = new QName("http://ws.das.ubp.edu.ar/", "LoginWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9090/LoginWSPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LoginWSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:9090/LoginWSPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LoginWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LoginWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginWSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public LoginWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LoginWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LoginWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns LoginWS
     */
    @WebEndpoint(name = "LoginWSPort")
    public LoginWS getLoginWSPort() {
        return super.getPort(LoginWSPort, LoginWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginWS
     */
    @WebEndpoint(name = "LoginWSPort")
    public LoginWS getLoginWSPort(WebServiceFeature... features) {
        return super.getPort(LoginWSPort, LoginWS.class, features);
    }

}
