
package ar.edu.ubp.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.6
 * Thu Nov 08 13:21:16 ART 2018
 * Generated source version: 3.2.6
 */

@XmlRootElement(name = "getUsuarioResponse", namespace = "http://ws.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getUsuarioResponse", namespace = "http://ws.das.ubp.edu.ar/")

public class GetUsuarioResponse {

    @XmlElement(name = "return")
    private ar.edu.ubp.das.beans.UsuarioBean _return;

    public ar.edu.ubp.das.beans.UsuarioBean getReturn() {
        return this._return;
    }

    public void setReturn(ar.edu.ubp.das.beans.UsuarioBean new_return)  {
        this._return = new_return;
    }

}

